---
before_script:
  - "export GRADLE_USER_HOME=`pwd`/.gradle"
build:
  artifacts:
    paths:
      - build
      - .gradle
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - build
      - .gradle
    policy: push
  script:
    - "gradle --build-cache assemble"
    - "gradle --build-cache shadowJar"
  stage: production
image: "gradle:alpine"
stages:
  - quality_assurance
  - production
test:
  allow_failure: true
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - build
      - .gradle
    policy: pull
  script:
    - "gradle check"
  stage: quality_assurance
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
