---
logging:
  level:
    root: info
    #org.hibernate.SQL: DEBUG
    #org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    #org.springframework.jdbc.core.JdbcTemplate: DEBUG
    #org.springframework.jdbc.core.StatementCreatorUtils: TRACE
spring:
  datasource:
    dbcp2:
      default-schema: org.hibernate.dialect.Oracle10gDialect
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: ${DB_PASS:password}
    url: ${DB_CONN_URL:jdbc:oracle:thin:@localhost:1521:dbms}
    username: ${DB_USER:"user"}
  flyway:
    baseline-on-migrate: true
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  main:
    banner-mode: off
    web-application-type: none