CREATE TABLE COURSES (
    COURSE_ID	CHAR(6),
    COURSE_TITLE	VARCHAR(100),
    STAFF_NAME	VARCHAR(100),
    SECTION		CHAR(3)
);

CREATE TABLE STUDENTS (
    STUDENT_ID	CHAR(8),
    STUDENT_NAME	VARCHAR(100),
    DEPARTMENT	VARCHAR(100),
    ADDRESS		VARCHAR(255),
    BIRTHDATE	DATE,
    GENDER		VARCHAR(6)
);

CREATE TABLE ENROLLMENT (
    STUDENT_ID	CHAR(8),
    COURSE_ID	CHAR(6),
    REG_DATE	DATE,
    GRADE		NUMBER(3,0)
);